#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34011
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("POIApp.Resource", IsApplication=true)]

namespace POIApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f040000
			public const int useCustomAppData = 2130968576;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_app = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_new = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_refresh = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int actionNew = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int actionRefresh = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int addrTextView = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int distanceTextView = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout1 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int nameTextView = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int poiImageView = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int poiListView = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int integer = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int POIList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int POIListItem = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int POIListViewMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MenuNew = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int MenuRefresh = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int pathAppData = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int pathAppDataFolder = 2131099652;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
