#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("POIApp.Resource", IsApplication=true)]

namespace POIApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f040000
			public const int useCustomAppData = 2130968576;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int floatMetersToMilesMultiplier = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_app = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_locate = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_map = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_new = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_new_picture = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_refresh = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_save = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090018
			public const int actionDelete = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int actionNew = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int actionRefresh = 2131296282;
			
			// aapt resource value: 0x7f090017
			public const int actionSave = 2131296279;
			
			// aapt resource value: 0x7f090007
			public const int addrEditText = 2131296263;
			
			// aapt resource value: 0x7f090015
			public const int addrTextView = 2131296277;
			
			// aapt resource value: 0x7f090005
			public const int descrEditText = 2131296261;
			
			// aapt resource value: 0x7f090016
			public const int distanceTextView = 2131296278;
			
			// aapt resource value: 0x7f09000d
			public const int latEditText = 2131296269;
			
			// aapt resource value: 0x7f090001
			public const int linearLayout1 = 2131296257;
			
			// aapt resource value: 0x7f090010
			public const int locationImageButton = 2131296272;
			
			// aapt resource value: 0x7f09000e
			public const int longEditText = 2131296270;
			
			// aapt resource value: 0x7f090011
			public const int mapImageButton = 2131296273;
			
			// aapt resource value: 0x7f090003
			public const int nameEditText = 2131296259;
			
			// aapt resource value: 0x7f090014
			public const int nameTextView = 2131296276;
			
			// aapt resource value: 0x7f090012
			public const int photoImageButton = 2131296274;
			
			// aapt resource value: 0x7f09000f
			public const int poiImageView = 2131296271;
			
			// aapt resource value: 0x7f090013
			public const int poiListView = 2131296275;
			
			// aapt resource value: 0x7f090000
			public const int scrollView1 = 2131296256;
			
			// aapt resource value: 0x7f090008
			public const int tableLayout1 = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int tableRow2 = 2131296265;
			
			// aapt resource value: 0x7f09000c
			public const int tableRow3 = 2131296268;
			
			// aapt resource value: 0x7f090002
			public const int textView10 = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int textView11 = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int textView12 = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int textView21 = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int textView22 = 2131296267;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int integer = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int POIDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int POIList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int POIListItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int POIDetailMenu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int POIListViewMenu = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MenuNew = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int MenuRefresh = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int labelCancel = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int labelNo = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int labelOk = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int labelYes = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int msgDialogPOIDelete = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int msgDialogPOIGetLocation = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int msgDialogRequestEnableGPSProvider = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int msgToastPOIDeleted = 2131165201;
			
			// aapt resource value: 0x7f07000b
			public const int msgValidatePOILatitudeDecimal = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int msgValidatePOILatitudeDecimalRange = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int msgValidatePOILongitudeDecimal = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int msgValidatePOILongitudeDecimalRange = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int msgValidatePOIName = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int pathAppData = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int pathAppDataFolder = 2131165188;
			
			// aapt resource value: 0x7f070014
			public const int unitOfLengthKm = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int unitOfLengthMetre = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int unitOfLengthMiles = 2131165202;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
